config/routes.rb
Rails.application.routes.draw do

  get 'tags/:tag', to: 'campaigns#index', as: :tag
  get 'categories/:category', to: 'campaigns#category', as: :category
  get 'popular', to: 'campaigns#popular', as: :popular
  get 'troll/show'

  resources :sessions
  resources :campaigns do
    resources :rewards
    resources :comments
  end

  resources :users do
    resources :pledges
    resources :comments
  end

  namespace :my do
    resources :campaigns
    resources :rewards, only: [:show, :index]
    resources :pledges, only: [:index, :show, :update, :destroy]
  end

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"

  post '/rewards/:id/pledge', to: 'rewards#pledge', as: :pledge

  root 'campaigns#index'

  get "/pages/about", :to => 'pages#about'

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  has_many :rewards
  has_many :users, through: :rewards
  has_many :comments, as: :commentable
  accepts_nested_attributes_for :rewards, :reject_if => :all_blank, :allow_destroy => true
  belongs_to :user
  validates :name, :description, :goal, :start_date, :end_date, :category, :presence => true
  validates :description, length: { maximum: 250 }
  validate :appropriate_dates
  acts_as_taggable

  def total_earned
    total = 0
    self.rewards.each do |r|
      total += (r.amount * r.pledges.count)
    end
    total
  end

  def number_of_backers
    total = 0
    self.rewards.each do |r|
      total += r.pledges.count
    end
    total
  end

  def appropriate_dates
    if start_date && end_date
      if start_date > end_date
        errors.add(:base, "You can't end your campaign before it starts!")
      end
    end
  end

  def funded_status
    if self.goal < self.total_earned
      funded_status = true
    end
    funded_status
  end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :require_login, :except => [:show, :index]
  before_action :authenticate_creator, :only => [:edit, :update, :destroy]
  def index
    if params[:tag]
      @campaigns = Campaign.tagged_with(params[:tag])
    else
      @campaigns = Campaign.all
    end
  end

  def show
    @campaign = Campaign.find(params[:id])
    @rewards = @campaign.rewards.all
    @pledges = Pledge.all
    @reward_campaign = @campaign.rewards
    @comments = @campaign.comments.all

    if current_user
      @comment = @campaign.comments.build
    end

    if current_user
      rewarded = current_user.rewards.select(:campaign_id, :id).distinct
      rewarded.each do |r|
        if @campaign.id == r.campaign_id
          @pledge_status = true
          break
        else
          @pledge_status = false
        end
      end
    end
  end

  def new
    @campaign = Campaign.new
  end

  def create
    @campaign = current_user.campaigns.build(campaign_params)

    if @campaign.save
      redirect_to campaigns_path
    else
      render :new
    end
  end

  def edit
    @campaign = Campaign.find(params[:id])
  end

  def update
    @campaign = Campaign.find(params[:id])

    if @campaign.update_attributes(campaign_params)
      redirect_to campaign_path(@campaign)
    else
      render :edit
    end
  end

  def category
    @campaigns = Campaign.where(:category => params[:category])
  end

  def popular
    @funded_array = []
    Campaign.all.each do |f|
      if f.funded_status == true
        @funded_array << f
      end
    end
    @backed = Campaign.all.sort_by { |b| -1*b.number_of_backers }
  end

  private
  def campaign_params
    params.require(:campaign).permit(:name, :description, :goal, :begin_time, :finish_time, :start_date, :end_date, :category, :tag_list, :popular, :pitch, rewards_attributes: [:name, :description, :amount, :_destroy])
  end

  def authenticate_creator
    if current_user.id != Campaign.find(params[:id]).user_id
    redirect_to troll_show_path
    end
  end
end

app/controllers/my/campaigns_controller.rb
class My::CampaignsController < ApplicationController
  before_filter :require_login
  before_filter :require_campaign

  def index
    @user = current_user
    @campaigns = current_user.campaigns.order('campaigns.created_at DESC').all
    @pledges = current_user.pledges.uniq
  end

  def new
    @campaign = current_user.campaigns.build
  end

  def edit
    @campaign = current_user.campaigns.find(params[:id])
  end

  def update
    if @campaign.update_attributes(params[:campaign])
      redirect_to [:my, :campaigns], notice: "Campaign updated!"
    else
      render :edit
    end
  end

  def create
    @campaign = current_user.campaigns.build(params[:campaign])
    if @project.save
      redirect_to [:my, :campaigns], notice: "Campaign created!"
    else
      render :new
    end
  end

  def destroy
  end

  private
  def require_campaign
    @campaign = current_user.campaigns.all
  end
end

app/controllers/my/pledges_controller.rb
class My::PledgesController < ApplicationController
  before_filter :require_login
  before_filter :require_pledge

  def index
    @pledges = current_user.pledges.order('pledges.created_at DESC').all
  end

  def update
    if @campaign.update_attributes(params[:campaign])
      redirect_to [:my, :campaigns], notice: "Campaign updated!"
    else
      render :edit
    end
  end

  def show
    @pledge = current_user.pledges.find(params[:id])
  end

  def destroy
  end

  private
  def require_pledge
    @pledge = current_user.pledges.all
  end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
  def category_type
    [
      ['Art'],
      ['Comics'],
      ['Crafts'],
      ['Dance'],
      ['Design'],
      ['Fashion'],
      ['Film & Video'],
      ['Food'],
      ['Games'],
      ['Journalism'],
      ['Music'],
      ['Photography'],
      ['Publishing'],
      ['Technology'],
      ['Theatre']
    ]
  end
end

app/helpers/my/campaigns_helper.rb
module My::CampaignsHelper
end

app/helpers/my/pledges_helper.rb
module My::PledgesHelper
end

app/views/my/campaigns/_campaign.html.erb
<div>
 <strong><%= link_to campaign.name, [:edit, campaign] %></strong><br/>
 <p>Description: <%= campaign.description %></p>
</div>

app/views/my/campaigns/_form.html.erb
<div>
 <%= form.text_field :name, placeholder: 'Campaign Title' %>
</div>

<div>
 <%= form.number_field :goal, placeholder: 'Funding Goal Amount' %>
</div>
<div>
 <%= form.text_area :description, rows: 10, placeholder: 'Detailed description' %>
</div>

app/views/my/campaigns/_user.html.erb
<div>
 <p>$<%= user.name %></p>
</div>

app/views/my/campaigns/edit.html.erb
<h1>Edit <%= @campaign.name %></h1>

<div class="well">
 <%= link_to [:my, :campaigns], :class => 'btn btn-small' do %>
  &laquo; My Campaigns
 <% end %>
</div>

<%= form_for [:my, @campaign] do |f| %>
  <%= render f %>
  <div class="form-actions">
    <%= f.submit 'Update Campaign', class: 'btn' %>
  </div>
<% end %>

app/views/my/campaigns/index.html.erb
<div>
  <br>
  <br>
  <div class="row campaign">
    <h1>My Account Info</h1>
    <div class="large-10 columns">
      <%= render @user %>
    </div>
    <div class="large-2 columns">
      <%= link_to 'Edit Info', edit_user_url(current_user) %>
    </div>
  </div>
  <br>
  <br>
  
  <div class="row campaign">
    <h1>My Campaigns</h1>
    <div class="large-10 columns">
      <%= render @campaigns %>
      <%= link_to '+ New Campaign', [:new, :campaign], :class => "button [radius round]" %>
    </div>
  </div>
  <br>
  <br>
  
  <div class="row campaign">
    <h1>Campaigns Backed</h1>
    <%= render @pledges %>
    <div class="large-12 columns">
      <p class="text-center">-------------------------------------------------------------------------------------------------------------------------------------</p>
      <% sum = 0 %>
      <% @user.pledges.each do |p| %>
        <% sum += p.reward.amount %>
      <% end %>
      <h3 class="text-center"><strong>Total Amount Donated: </strong>$<%= sum %></h3>
      <br>
      <br>
    </div>
  </div>
  <br>
  <br>
</div>

app/views/my/campaigns/new.html.erb
<h1>New Campaign</h1>
<div class="well">
 <%= link_to [:my, :campaigns], :class => 'btn btn-small' do %>
 &laquo; My Campaigns
 <% end %>
</div>

<%= form_for [:my, @campaign] do |f| %>
  <%= render f %>
 <div class="form-actions">
 <%= f.submit 'Publish Campaign', class: 'btn' %>
 </div>
<% end %>