config/routes.rb
Rails.application.routes.draw do

  get 'tags/:tag', to: 'campaigns#index', as: :tag
  get 'categories/:category', to: 'campaigns#category', as: :category
  get 'popular', to: 'campaigns#popular', as: :popular
  get 'troll/show'

  resources :sessions
  resources :campaigns do
    resources :rewards
    resources :comments
  end

  resources :users do
    resources :pledges
    resources :comments
  end

  namespace :my do
    resources :campaigns
    resources :rewards, only: [:show, :index]
    resources :pledges, only: [:index, :show, :update, :destroy]
  end

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"

  post '/rewards/:id/pledge', to: 'rewards#pledge', as: :pledge

  root 'campaigns#index'

  get "/pages/about", :to => 'pages#about'

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  has_many :rewards
  has_many :users, through: :rewards
  has_many :comments, as: :commentable
  accepts_nested_attributes_for :rewards, :reject_if => :all_blank, :allow_destroy => true
  belongs_to :user
  validates :name, :description, :goal, :start_date, :end_date, :category, :presence => true
  validates :description, length: { maximum: 250 }
  validate :appropriate_dates
  acts_as_taggable

  def total_earned
    total = 0
    self.rewards.each do |r|
      total += (r.amount * r.pledges.count)
    end
    total
  end

  def number_of_backers
    total = 0
    self.rewards.each do |r|
      total += r.pledges.count
    end
    total
  end

  def appropriate_dates
    if start_date && end_date
      if start_date > end_date
        errors.add(:base, "You can't end your campaign before it starts!")
      end
    end
  end

  def funded_status
    if self.goal < self.total_earned
      funded_status = true
    end
    funded_status
  end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :require_login, :except => [:show, :index]
  before_action :authenticate_creator, :only => [:edit, :update, :destroy]
  def index
    if params[:tag]
      @campaigns = Campaign.tagged_with(params[:tag])
    else
      @campaigns = Campaign.all
    end
  end

  def show
    @campaign = Campaign.find(params[:id])
    @rewards = @campaign.rewards.all
    @pledges = Pledge.all
    @reward_campaign = @campaign.rewards
    @comments = @campaign.comments.all

    if current_user
      @comment = @campaign.comments.build
    end

    if current_user
      rewarded = current_user.rewards.select(:campaign_id, :id).distinct
      rewarded.each do |r|
        if @campaign.id == r.campaign_id
          @pledge_status = true
          break
        else
          @pledge_status = false
        end
      end
    end
  end

  def new
    @campaign = Campaign.new
  end

  def create
    @campaign = current_user.campaigns.build(campaign_params)

    if @campaign.save
      redirect_to campaigns_path
    else
      render :new
    end
  end

  def edit
    @campaign = Campaign.find(params[:id])
  end

  def update
    @campaign = Campaign.find(params[:id])

    if @campaign.update_attributes(campaign_params)
      redirect_to campaign_path(@campaign)
    else
      render :edit
    end
  end

  def category
    @campaigns = Campaign.where(:category => params[:category])
  end

  def popular
    @funded_array = []
    Campaign.all.each do |f|
      if f.funded_status == true
        @funded_array << f
      end
    end
    @backed = Campaign.all.sort_by { |b| -1*b.number_of_backers }
  end

  private
  def campaign_params
    params.require(:campaign).permit(:name, :description, :goal, :begin_time, :finish_time, :start_date, :end_date, :category, :tag_list, :popular, :pitch, rewards_attributes: [:name, :description, :amount, :_destroy])
  end

  def authenticate_creator
    if current_user.id != Campaign.find(params[:id]).user_id
    redirect_to troll_show_path
    end
  end
end

app/controllers/my/campaigns_controller.rb
class My::CampaignsController < ApplicationController
  before_filter :require_login
  before_filter :require_campaign

  def index
    @user = current_user
    @campaigns = current_user.campaigns.order('campaigns.created_at DESC').all
    @pledges = current_user.pledges.uniq
  end

  def new
    @campaign = current_user.campaigns.build
  end

  def edit
    @campaign = current_user.campaigns.find(params[:id])
  end

  def update
    if @campaign.update_attributes(params[:campaign])
      redirect_to [:my, :campaigns], notice: "Campaign updated!"
    else
      render :edit
    end
  end

  def create
    @campaign = current_user.campaigns.build(params[:campaign])
    if @project.save
      redirect_to [:my, :campaigns], notice: "Campaign created!"
    else
      render :new
    end
  end

  def destroy
  end

  private
  def require_campaign
    @campaign = current_user.campaigns.all
  end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
  def category_type
    [
      ['Art'],
      ['Comics'],
      ['Crafts'],
      ['Dance'],
      ['Design'],
      ['Fashion'],
      ['Film & Video'],
      ['Food'],
      ['Games'],
      ['Journalism'],
      ['Music'],
      ['Photography'],
      ['Publishing'],
      ['Technology'],
      ['Theatre']
    ]
  end
end

app/helpers/my/campaigns_helper.rb
module My::CampaignsHelper
end

app/views/campaigns/_form.html.erb
<div class="row">
  <% if @campaign.errors.any? %>
    <% @campaign.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  <% end %>
  <br>
  <%= form_for @campaign do |f| %>
    <div class="large-10 columns">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <br>
    <div class="large-10 columns">
      <%= f.label :description, "Description (Maximum 250 characters. We'll let you write the full pitch later!)" %>
      <%= f.text_field :description %>
    </div>
    <br>
    <div class="large-10 columns">
      <%= f.label :goal %>
      <%= f.number_field :goal %>
    </div>
    <br>
    <div class="large-5 columns">
      <%= f.label :start_date %>
      <%= f.date_field :start_date %>
    </div>
    <br>
    <div class="large-5 columns">
      <%= f.label :end_date %>
      <%= f.date_field :end_date %>
    </div>
    <br>
    <div class="large-10 columns">
      <%= f.label :category %>
      <%= f.select :category, category_type %>
    </div>
    <div class="large-10 columns">
      <%= f.label :tag_list, "Tags (separated by commas)" %>
      <%= f.text_field :tag_list %>
    </div>
    <div class="large-10 columns">
      <%= f.label :pitch %>
      <%= f.text_area :pitch %>
    </div>
    <br>
    <div class="large-10 columns">
      <h3>Rewards</h3>
    </div>
    <br>
    <div class="large-10 columns" style="display: block" class="cocoon">
      <% f.fields_for :rewards do |reward| %>
        <%= render 'reward_fields', :f => reward %>
      <% end %>
      <p><%= link_to_add_association 'Add Reward', f, :rewards %></p>

    </div>

    <div class="large-12 columns">
      <%= f.submit :submit, :class => "button" %>
    </div>
  </div>

  <% end %>

app/views/campaigns/_reward_fields.html.erb
<div class="nested-fields">
  <p>Reward <span class="reward-counter">0</span></p>
  <div style="display: block">
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :description, "Description (Maximum 250 characters.)" %>
      <%= f.text_field :description %>
      <%= f.label :amount %>
      <%= f.number_field :amount %>
  </div>
  <%= link_to_remove_association "Remove Reward", f %>
</div>
<br>
<br>

app/views/campaigns/_rewards.html.erb
<div class="highlight">
  <% if @pledge_status == true %>
    <p> You have donated. Thank You! </p>
  <% else %>
    <p> Do you want to donate? </p>
  <% end %>
</div>

<h2>Rewards</h2>

  <% @total = 0 %>
  <% @rewards.each do |r| %>
    <div class="rewards" id="<%= r.id %>">
<!-- Text to be shown over hover -->
    <span class="text-content"><span>Donate now!</span></span>
    
    <br>
    <p><%= r.description %></p>
    <p>$<%= r.amount %></p> 
    <p ><%= r.name %></p>
    <p>Number claimed <%= ((@pledges.where(:reward_id => r.id).count)) %></p>
    </div>
    <div id="dialog<%=r.id%>" title="Back this Campaign">
      <%= form_tag pledge_path(r.id),:remote => true, id: r.id do %>
          <div>
            <p>Reward Description:</p>
            <p><%=r.description%></p>
            <p>$<%=r.amount%></p>
            <br><br>
            <p><%=submit_tag "Complete Pledge", class: "pledge_create"%></p>
          </div>
      <% end %>
    </div>


  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css">
  <script type='text/javascript'>

    $(function() {
      $( "#dialog<%=r.id%>" ).dialog({
        autoOpen: false,
        show: {
          effect: "blind",
          duration: 100
        },
        hide: {
          effect: "explode",
          duration: 1000
        }
      });

      $("#dialog<%=r.id%>").submit(function () {
        $("#dialog<%=r.id%>").dialog( "close" );
        $( "#<%=r.id%>" ).click(function() {
        $( "#dialog<%=r.id%>" ).dialog( "open" );
        });
      });

      $( "#<%=r.id%>" ).click(function() {
        $( "#dialog<%=r.id%>" ).dialog( "open" );
      });
    });

  </script>
<% end %>

app/views/campaigns/_sidebar.html.erb
<div class="rewards">
<span class="campaign_header" id = "total_earned">
  $<%= @campaign.total_earned %>
</span>
<p>pledged of $<%= @campaign.goal %> goal.</p>
<span class="campaign_header"><%= @campaign.number_of_backers %></span>
<p>backers</p>

<% if @campaign.end_date < Time.now %>
  <p>Campaign over!</p>
<% else %>
  <span class="campaign_header">
    <%= (@campaign.end_date - Date.today).round %>
  </span>
  <p> days to go</p>
<% end %>

<p style="font-size: .8rem;">Category: <%= link_to @campaign.category, category_path(@campaign.category) %></p>
<p style="font-size: .8rem;">Tags: <%= raw @campaign.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')%></p>
<p style="font-size: .8rem;">Campaign was created by <%= @campaign.user.email %></p>

<div id="campaign_status">
  <% if @campaign.goal > @campaign.total_earned %>
    <p style="font-size: .8rem;">Campaign will only be funded if goal is reached by: <%= @campaign.end_date %></p>
  <% else %>
    <p style="font-size: 3rem" class="highlight">Campaign funded!</p>
  <% end %>
</div>

<div class="highlight">
  <% if current_user %>
    <% if @pledge_status == true %>
      <p> You have donated. Thank You! </p>
    <% else %>
      <p> Do you want to donate? </p>
    <% end %>
  <% else %>
    <p><%= link_to "Log in", login_path %> to reap some rewards!</p>
  <% end %>
</div>
</div>
<h2>Rewards</h2>

  <% @total = 0 %>
  <% @rewards.each do |r| %>
    <div id="<%= r.id %>">
    <div class="rewards">
<!-- Text to be shown over hover -->
    <span class="text-content"><span>Donate now!</span></span>

    <br>
    
    <p>Pledge $<%= r.amount %> for <%= r.name %></p>
    <p>Number claimed <%= ((@pledges.where(:reward_id => r.id).count)) %></p>
    <p><%= r.description %></p>
    </div>

    </div>
    <div id="dialog<%=r.id%>" title="Back this Campaign">
      <%= form_tag pledge_path(r.id),:remote => true, id: r.id do %>
          <div>
            <p>Reward Description:</p>
            <p><%=r.description%></p>
            <p>$<%=r.amount%></p>
            <br><br>
            <p><%=submit_tag "Complete Pledge", class: "pledge_create"%></p>
          </div>
      <% end %>
    </div>

  <script type='text/javascript'>

    $(function() {
      $( "#dialog<%=r.id%>" ).dialog({
        autoOpen: false,
        show: {
          effect: "blind",
          duration: 100
        },
        hide: {
          effect: "explode",
          duration: 1000
        }
      });

      $("#dialog<%=r.id%>").submit(function () {
        $("#dialog<%=r.id%>").dialog( "close" );
        $( "#<%=r.id%>" ).click(function() {
        $( "#dialog<%=r.id%>" ).dialog( "open" );
        });
      });

      $( "#<%=r.id%>" ).click(function() {
        $( "#dialog<%=r.id%>" ).dialog( "open" );
      });
    });

  </script>
<% end %>

app/views/campaigns/category.html.erb
<% @campaigns.each do |c| %>
  <h2><%= link_to c.name, campaign_path(c) %></h2>
  <p>Tags:  <%= raw c.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')%></p>
<% end %>

app/views/campaigns/edit.html.erb
  <h1>Edit <%= @campaign.name %></h1>

<%= render 'form' %>

app/views/campaigns/index.html.erb
<br>
<h1> Discover Campaigns </h1>
<br>
<% @campaigns.each do |c| %>
  <h3><%= link_to c.name, campaign_path(c) %></h3>
  <p>
    <%= c.description %>
    <br>
    Tags:  <%= raw c.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')%>
  </p>
  <div class="progressbar" data-value="<%= c.total_earned %>" data-max="<%= c.goal %>"></div>

    <div class="row left full-width">
      <p class="small-1 columns">
        <strong><%= (c.total_earned.to_f / c.goal)*100 %>%</strong>
        <br> funded 
      </p>
      <p class="small-1 columns">
        <strong>$<%= c.total_earned %></strong>
        <br> pledged
      </p>
      <p class="small-1 columns">
        <strong><%= c.number_of_backers %></strong>
        <br> backers
      </p>
      <p class="small-1 columns">
        <% if c.end_date < Time.now %>
          <strong><p>Campaign over!</p></strong>
        <% else %>
          <strong><%= (c.end_date - Date.today).round %></strong>
          <br> days to go
        <% end %>
      </p>
      <p class="small-1 columns"></p>
    </div>
  <br>
  <br>
  <br>
  <br>
<% end %>

<script>
  
  $(function() {
    $( ".progressbar" ).each(function() {
      var self = $(this)
          value = self.data('value'),
          max = self.data('max');

      self.progressbar({
        value: value,
        max: max
      });
    });
  });


// $(function() {  
//   $('.progress_bar').each(function() {
// var progressbar = $(this),
//       progressLabel = $(this).find( ".progress-label" ),
//     progressvalue = $(this).attr('value');
// console.log(progressvalue);     
      
//     progressbar.progressbar({
//       value: false,
//       change: function() {
       
//         progressLabel.text( progressbar.progressbar( "value" ) + "% Complete" );
//       },
//       complete: function() {
//         progressLabel.text( "Complete!" );
//       }
//     });
 
//     function progress() {
                
//       var val = progressbar.progressbar( "value" ) || 0;
 
//       progressbar.progressbar( "value", val + 1 )
//         .removeClass("beginning middle end")
//         .addClass(val < 40 ? "beginning" : val < 80 ? "middle" : "end");
        
 
//       if ( val < progressvalue ) {
//         setTimeout( progress, 100 );
//       }
//     }
 
//     setTimeout( progress, 100 );
//        });
//     });
</script>

app/views/campaigns/new.html.erb
<div class="row">
  <h1 class="large-12 columns">Create a new campaign</h1>
  <br>
  <br>
  <%= render 'form' %>
</div>

app/views/campaigns/popular.html.erb
<h1>Campaigns that have been funded</h1>
  <% if @funded_array.count > 0 %>
    <% @funded_array.each do |f| %>
      <h3><%= link_to f.name, campaign_path(f) %></h3>
      <p>Initial goal: <%= f.goal %></p>
      <p>Funds raised: <%= f.total_earned %></p>
    <% end %>
  <% else %>
    <p>No campaign has been funded yet!</p>
<% end %>

<h1>Campaigns with the most backers</h1>
<% @backed.each do |b| %>
  <h3><%= link_to b.name, campaign_path(b) %></h3>
  <p><%= b.number_of_backers %> backers</p>
  <br>
<% end %>

app/views/campaigns/show.html.erb
<section>

  <div class="campaign_title"> <%= @campaign.name %>
  </div>
  <div class="campaign_user"> Created by: <%= link_to @campaign.user.email, user_path(@campaign.user) %>
  </div>

  <div class="row campaign">

    <div class="large-8 columns">
      <div class="campaign_pic">
        <source><iframe width="640" height="480" src="https://www.kickstarter.com/projects/413902085/black-market-debut-album-by-erin-cooper-gay/widget/video.html" frameborder="0" scrolling="no"> </iframe></source>
      </div>
      <div class="campaign_description">
        <p><%= @campaign.pitch %></p>
      </div>
      
      <div id="campaign_comments">
        <%= render 'comments' %>
      </div>

      <div class="new_comment_form">
        <% if current_user %>
          <%= form_for [@campaign, @comment], :remote => true, id:"new_comment" do |f| %>
            <div class="large-10 columns">
              <%= f.label :body, "Comment" %>
              <%= f.text_field :body %>
            </div>
           <% end %>
         <% end %>
      </div>
    </div>

    <div class="large-4 columns campaign_info">
      <div id="sidebar">
        <%= render 'sidebar' %>
      </div>
    </div>

 </div>
</section>