config/routes.rb
Rails.application.routes.draw do

  get 'tags/:tag', to: 'campaigns#index', as: :tag
  get 'categories/:category', to: 'campaigns#category', as: :category
  get 'popular', to: 'campaigns#popular', as: :popular
  get 'troll/show'

  resources :sessions
  resources :campaigns do
    resources :rewards
    resources :comments
  end

  resources :users do
    resources :pledges
    resources :comments
  end

  namespace :my do
    resources :campaigns
    resources :rewards, only: [:show, :index]
    resources :pledges, only: [:index, :show, :update, :destroy]
  end

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"

  post '/rewards/:id/pledge', to: 'rewards#pledge', as: :pledge

  root 'campaigns#index'

  get "/pages/about", :to => 'pages#about'

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  has_many :rewards
  has_many :users, through: :rewards
  has_many :comments, as: :commentable
  accepts_nested_attributes_for :rewards, :reject_if => :all_blank, :allow_destroy => true
  belongs_to :user
  validates :name, :description, :goal, :start_date, :end_date, :category, :presence => true
  validates :description, length: { maximum: 250 }
  validate :appropriate_dates
  acts_as_taggable

  def total_earned
    total = 0
    self.rewards.each do |r|
      total += (r.amount * r.pledges.count)
    end
    total
  end

  def number_of_backers
    total = 0
    self.rewards.each do |r|
      total += r.pledges.count
    end
    total
  end

  def appropriate_dates
    if start_date && end_date
      if start_date > end_date
        errors.add(:base, "You can't end your campaign before it starts!")
      end
    end
  end

  def funded_status
    if self.goal < self.total_earned
      funded_status = true
    end
    funded_status
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body, :presence => true
  belongs_to :commentable, polymorphic: true

end

app/models/pledge.rb
class Pledge < ActiveRecord::Base
  belongs_to :reward
  belongs_to :user
  has_one :campaign, :through => :reward
  validates :user_id, :presence => true
end

app/models/reward.rb
class Reward < ActiveRecord::Base
  belongs_to :campaign
  has_many :pledges
  validates :name, :description, :presence => true
  validates :description, :length => { maximum: 250 }
  validates :amount, :numericality => {:only_integer => true}
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :campaigns
  has_many :pledges
  has_many :rewards, through: :pledges
  has_many :comments, as: :commentable
  authenticates_with_sorcery!

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :load_parent

  def create
    @comment = @commentable.comments.build(comment_params)
    @user = User.find(current_user)
    @comment.user_id = @user.id
    @comments = @commentable.comments

    respond_to do |format|
      if @comment.save
        format.html { redirect_to :back }
        format.js {}
      else
        format.html { redirect_to :root_path, :notice => "Error in creating comment" }
        format.js {}
      end
    end

  end

  def edit
  end

  def destroy
  end

  private
  def load_parent
    if params[:campaign_id]
      @commentable = Campaign.find(params[:campaign_id])
    elsif params[:user_id]
      @commentable = User.find(params[:user_id])
    end
  end

  def comment_params
    params.require(:comment).permit(:body)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController

  def pledge
    @reward = Reward.find(params[:id])
    @pledge = @reward.pledges.create (attributes = {user_id: current_user.id})
    @rewards = Reward.where("campaign_id = ?", @reward.campaign_id)
    @pledges = Pledge.all
    @campaign =  @reward.campaign

    rewarded = current_user.rewards.select(:campaign_id, :id).distinct
    rewarded.each do |r|
      if @campaign.id == r.campaign_id
        @pledge_status = true
        break
      else
        @pledge_status = false
      end
    end

    respond_to do |format|
      if @pledge.save
        format.html {redirect_to campaigns_path, notice: "Pledge accepted!"}
        format.js
      else
        format.html {render 'campaigns/show', alert: "There was an error"}
        format.js
      end
    end
  end
end

app/controllers/troll_controller.rb
class TrollController < ApplicationController
  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @comments = @user.comments.all
    @comment = @user.comments.build
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_path, :notice => "Signed up!"
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to [:my, :campaigns], notice: "User Info Updated!"
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
  def category_type
    [
      ['Art'],
      ['Comics'],
      ['Crafts'],
      ['Dance'],
      ['Design'],
      ['Fashion'],
      ['Film & Video'],
      ['Food'],
      ['Games'],
      ['Journalism'],
      ['Music'],
      ['Photography'],
      ['Publishing'],
      ['Technology'],
      ['Theatre']
    ]
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pledges_helper.rb
module PledgesHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/troll_helper.rb
module TrollHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Crowdfunder" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag "application" %>


  </head>

  <body>
    <div class="container">
    <div class="fixed">

        <nav class="top-bar" data-topbar>
          <ul class="title-area">
            <li class="name">
              <h1><a href="/">crowd<span id="funder">Funder</span></a></h1>
            </li>
          </ul>
          <!-- Right Nav Section -->
          <section class="top-bar-section">
            <ul class="right">
              <% if current_user%>
                <li class="has-dropdown">
                  <a href="#"><%= current_user.email %></a>
                  <!-- <%= link_to "Info", [:my, :campaigns] %> -->

                  <ul class="dropdown">
                    <li><%= link_to "Account Info", [:my, :campaigns] %></li>
                    <li> <%= link_to "Logout", logout_path %> </li>
                  </ul>
                </li>
              <% else %>
                <li><%= link_to "Sign Up", signup_path %></li>
                <li><%= link_to "Log In", login_path %></li>
              <% end %>
            </ul>

          <!-- Left Nav Section -->
          <ul class="left">
            <li><%= link_to "Campaigns", campaigns_path %></li>
            <li><%= link_to "Popular", popular_path %></li>
          </ul>
          </section>
        </nav>

    </div>
    
      <%= yield %>
      
       </div>
      <div id="footer">
        <%= link_to "Home", root_url %>
        <%= link_to "About", pages_about_url %>
      </div>

  </body>
</html>